# Generated by Django 3.2.9 on 2022-01-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
